// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace FlounderSharp
{
    /// <summary>A module used for managing shadow maps in 3D worlds.</summary>
    public unsafe partial class Shadows : global::FlounderSharp.IModule, IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 56)]
        public new partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::System.IntPtr vfptr_IModule;

            [FieldOffset(8)]
            internal global::System.IntPtr m_lightDirection;

            [FieldOffset(16)]
            internal uint m_shadowSize;

            [FieldOffset(20)]
            internal int m_shadowPcf;

            [FieldOffset(24)]
            internal float m_shadowBias;

            [FieldOffset(28)]
            internal float m_shadowDarkness;

            [FieldOffset(32)]
            internal float m_shadowTransition;

            [FieldOffset(36)]
            internal float m_shadowBoxOffset;

            [FieldOffset(40)]
            internal float m_shadowBoxDistance;

            [FieldOffset(48)]
            internal global::System.IntPtr m_shadowBox;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Shadows@fl@@QEAA@XZ")]
            internal static extern global::System.IntPtr ctor(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Shadows@fl@@QEAA@AEBV01@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr _0);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Get@Shadows@fl@@SAPEAV12@XZ")]
            internal static extern global::System.IntPtr Get();

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetLightDirection@Shadows@fl@@QEBAPEAVVector3@2@XZ")]
            internal static extern global::System.IntPtr GetLightDirection(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetLightDirection@Shadows@fl@@QEAAXAEBVVector3@2@@Z")]
            internal static extern void SetLightDirection(global::System.IntPtr instance, global::System.IntPtr lightDirection);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowSize@Shadows@fl@@QEBAIXZ")]
            internal static extern uint GetShadowSize(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowSize@Shadows@fl@@QEAAXAEBI@Z")]
            internal static extern void SetShadowSize(global::System.IntPtr instance, uint* shadowSize);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowPcf@Shadows@fl@@QEBAHXZ")]
            internal static extern int GetShadowPcf(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowPcf@Shadows@fl@@QEAAXAEBH@Z")]
            internal static extern void SetShadowPcf(global::System.IntPtr instance, int* shadowPcf);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowBias@Shadows@fl@@QEBAMXZ")]
            internal static extern float GetShadowBias(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowBias@Shadows@fl@@QEAAXAEBM@Z")]
            internal static extern void SetShadowBias(global::System.IntPtr instance, float* shadowBias);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowDarkness@Shadows@fl@@QEBAMXZ")]
            internal static extern float GetShadowDarkness(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowDarkness@Shadows@fl@@QEAAXAEBM@Z")]
            internal static extern void SetShadowDarkness(global::System.IntPtr instance, float* shadowDarkness);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowTransition@Shadows@fl@@QEBAMXZ")]
            internal static extern float GetShadowTransition(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowTransition@Shadows@fl@@QEAAXAEBM@Z")]
            internal static extern void SetShadowTransition(global::System.IntPtr instance, float* shadowTransition);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowBoxOffset@Shadows@fl@@QEBAMXZ")]
            internal static extern float GetShadowBoxOffset(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowBoxOffset@Shadows@fl@@QEAAXAEBM@Z")]
            internal static extern void SetShadowBoxOffset(global::System.IntPtr instance, float* shadowBoxOffset);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowBoxDistance@Shadows@fl@@QEBAMXZ")]
            internal static extern float GetShadowBoxDistance(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetShadowBoxDistance@Shadows@fl@@QEAAXAEBM@Z")]
            internal static extern void SetShadowBoxDistance(global::System.IntPtr instance, float* shadowBoxDistance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Flounder", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetShadowBox@Shadows@fl@@QEBAPEAVShadowBox@2@XZ")]
            internal static extern global::System.IntPtr GetShadowBox(global::System.IntPtr instance);
        }

        internal static new global::FlounderSharp.Shadows __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::FlounderSharp.Shadows(native.ToPointer(), skipVTables);
        }

        internal static global::FlounderSharp.Shadows __CreateInstance(global::FlounderSharp.Shadows.__Internal native, bool skipVTables = false)
        {
            return new global::FlounderSharp.Shadows(native, skipVTables);
        }

        private static void* __CopyValue(global::FlounderSharp.Shadows.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::FlounderSharp.Shadows.__Internal));
            global::FlounderSharp.Shadows.__Internal.cctor(ret, new global::System.IntPtr(&native));
            return ret.ToPointer();
        }

        private Shadows(global::FlounderSharp.Shadows.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Shadows(void* native, bool skipVTables = false)
            : base((void*) null)
        {
            __PointerAdjustment = 0;
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
            if (skipVTables)
                __OriginalVTables = new void*[] { *(void**) (__Instance + 0) };
            else
                SetupVTables(true);
        }

        /// <summary>Creates a new shadows module.</summary>
        public Shadows()
            : this((void*) null)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::FlounderSharp.Shadows.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor((__Instance + __PointerAdjustment));
            SetupVTables(GetType().FullName == "FlounderSharp.Shadows");
        }

        public Shadows(global::FlounderSharp.Shadows _0)
            : this((void*) null)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::FlounderSharp.Shadows.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(_0, null))
                throw new global::System.ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = _0.__Instance;
            __Internal.cctor((__Instance + __PointerAdjustment), __arg0);
            SetupVTables(GetType().FullName == "FlounderSharp.Shadows");
        }

        ~Shadows()
        {
            Dispose(false);
        }

        public override void Update()
        {
            var __slot = *(void**) ((IntPtr) __OriginalVTables[0] + 2 * 8);
            var ___UpdateDelegate = (global::FlounderSharp.Delegates.Action_IntPtr) Marshal.GetDelegateForFunctionPointer(new IntPtr(__slot), typeof(global::FlounderSharp.Delegates.Action_IntPtr));
            ___UpdateDelegate((__Instance + __PointerAdjustment));
        }

        /// <summary>Gets this engine instance.</summary>
        public static global::FlounderSharp.Shadows Get()
        {
            var __ret = __Internal.Get();
            global::FlounderSharp.Shadows __result0;
            if (__ret == IntPtr.Zero) __result0 = null;
            else if (global::FlounderSharp.Shadows.NativeToManagedMap.ContainsKey(__ret))
                __result0 = (global::FlounderSharp.Shadows) global::FlounderSharp.Shadows.NativeToManagedMap[__ret];
            else global::FlounderSharp.Shadows.NativeToManagedMap[__ret] = __result0 = (global::FlounderSharp.Shadows) global::FlounderSharp.Shadows.__CreateInstance(__ret);
            return __result0;
        }

        public global::FlounderSharp.Vector3 LightDirection
        {
            get
            {
                var __ret = __Internal.GetLightDirection((__Instance + __PointerAdjustment));
                global::FlounderSharp.Vector3 __result0;
                if (__ret == IntPtr.Zero) __result0 = null;
                else if (global::FlounderSharp.Vector3.NativeToManagedMap.ContainsKey(__ret))
                    __result0 = (global::FlounderSharp.Vector3) global::FlounderSharp.Vector3.NativeToManagedMap[__ret];
                else __result0 = global::FlounderSharp.Vector3.__CreateInstance(__ret);
                return __result0;
            }

            set
            {
                if (ReferenceEquals(value, null))
                    throw new global::System.ArgumentNullException("value", "Cannot be null because it is a C++ reference (&).");
                var __arg0 = value.__Instance;
                __Internal.SetLightDirection((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public uint ShadowSize
        {
            get
            {
                var __ret = __Internal.GetShadowSize((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowSize((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public int ShadowPcf
        {
            get
            {
                var __ret = __Internal.GetShadowPcf((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowPcf((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float ShadowBias
        {
            get
            {
                var __ret = __Internal.GetShadowBias((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowBias((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float ShadowDarkness
        {
            get
            {
                var __ret = __Internal.GetShadowDarkness((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowDarkness((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float ShadowTransition
        {
            get
            {
                var __ret = __Internal.GetShadowTransition((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowTransition((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float ShadowBoxOffset
        {
            get
            {
                var __ret = __Internal.GetShadowBoxOffset((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowBoxOffset((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float ShadowBoxDistance
        {
            get
            {
                var __ret = __Internal.GetShadowBoxDistance((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetShadowBoxDistance((__Instance + __PointerAdjustment), __arg0);
            }
        }

        /// <summary>Get the shadow box, so that it can be used by other class to test if engine.entities are inside the box.</summary>
        public global::FlounderSharp.ShadowBox ShadowBox
        {
            get
            {
                var __ret = __Internal.GetShadowBox((__Instance + __PointerAdjustment));
                global::FlounderSharp.ShadowBox __result0;
                if (__ret == IntPtr.Zero) __result0 = null;
                else if (global::FlounderSharp.ShadowBox.NativeToManagedMap.ContainsKey(__ret))
                    __result0 = (global::FlounderSharp.ShadowBox) global::FlounderSharp.ShadowBox.NativeToManagedMap[__ret];
                else __result0 = global::FlounderSharp.ShadowBox.__CreateInstance(__ret);
                return __result0;
            }
        }

        #region Virtual table interop

        // ~Shadows()
        private static global::FlounderSharp.Delegates.Action_IntPtr_int _dtorDelegateInstance;

        private static void _dtorDelegateHook(global::System.IntPtr instance, int delete)
        {
            if (!NativeToManagedMap.ContainsKey(instance))
                throw new global::System.Exception("No managed instance was found");

            var __target = (global::FlounderSharp.Shadows) NativeToManagedMap[instance];
            if (__target.__ownsNativeInstance)
                __target.SetupVTables();
            __target.Dispose(true);
        }

        // void Update() override
        private static global::FlounderSharp.Delegates.Action_IntPtr _UpdateDelegateInstance;

        private static void _UpdateDelegateHook(global::System.IntPtr instance)
        {
            if (!NativeToManagedMap.ContainsKey(instance))
                throw new global::System.Exception("No managed instance was found");

            var __target = (global::FlounderSharp.Shadows) NativeToManagedMap[instance];
            if (__target.__ownsNativeInstance)
                __target.SetupVTables();
            __target.Update();
        }

        private static void*[] __ManagedVTables;
        private static void*[] __ManagedVTablesDtorOnly;
        private static void*[] _Thunks;

        private void SetupVTables(bool destructorOnly = false)
        {
            if (__OriginalVTables != null)
                return;
            __OriginalVTables = new void*[] { *(void**) (__Instance + 0) };

            if (_Thunks == null)
            {
                _Thunks = new void*[2];
                _dtorDelegateInstance += _dtorDelegateHook;
                _Thunks[0] = Marshal.GetFunctionPointerForDelegate(_dtorDelegateInstance).ToPointer();
                _UpdateDelegateInstance += _UpdateDelegateHook;
                _Thunks[1] = Marshal.GetFunctionPointerForDelegate(_UpdateDelegateInstance).ToPointer();
            }

            if (destructorOnly)
            {
                if (__ManagedVTablesDtorOnly == null)
                {
                    __ManagedVTablesDtorOnly = new void*[1];
                    var vfptr0 = Marshal.AllocHGlobal(3 * 8);
                    __ManagedVTablesDtorOnly[0] = vfptr0.ToPointer();
                    *(void**) (vfptr0 + 0) = *(void**) (new IntPtr(*(void**) __Instance) + 0 + 0);
                    *(void**) (vfptr0 + 8) = _Thunks[0];
                    *(void**) (vfptr0 + 16) = *(void**) (new IntPtr(*(void**) __Instance) + 0 + 16);
                }

                *(void**) (__Instance + 0) = __ManagedVTablesDtorOnly[0];
            }
            else
            {
                if (__ManagedVTables == null)
                {
                    __ManagedVTables = new void*[1];
                    var vfptr0 = Marshal.AllocHGlobal(3 * 8);
                    __ManagedVTables[0] = vfptr0.ToPointer();
                    *(void**) (vfptr0 + 0) = *(void**) (new IntPtr(*(void**) __Instance) + 0 + 0);
                    *(void**) (vfptr0 + 8) = _Thunks[0];
                    *(void**) (vfptr0 + 16) = _Thunks[1];
                }

                *(void**) (__Instance + 0) = __ManagedVTables[0];
            }
        }

        #endregion
    }
}

namespace Std
{
    namespace Pair
    {
        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public unsafe partial struct __Internal_Ptr
        {
            [FieldOffset(0)]
            internal global::System.IntPtr first;

            [FieldOffset(8)]
            internal global::System.IntPtr second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public unsafe partial struct __Internalc__N_std_S_pair__1I____N_fl_S_FontCharacter
        {
            [FieldOffset(0)]
            internal int first;

            [FieldOffset(8)]
            internal global::System.IntPtr second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 80)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C___N_fl_S_ConfigKey
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::FlounderSharp.ConfigKey.__Internal second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 40)]
        public unsafe partial struct __Internalc__N_std_S_pair____N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C____N_fl_S_IModule
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::System.IntPtr second;
        }

        [StructLayout(LayoutKind.Explicit, Size = 40)]
        public unsafe partial struct __Internalc__N_std_S_pair__1__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C____N_fl_S_JointTransform
        {
            [FieldOffset(0)]
            internal global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C first;

            [FieldOffset(32)]
            internal global::System.IntPtr second;
        }
    }
}
