// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace AcidSharp
{
    public unsafe partial class Metadata
    {
        [StructLayout(LayoutKind.Explicit, Size = 0)]
        public partial struct __Internal
        {
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::AcidSharp.Metadata> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::AcidSharp.Metadata>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::AcidSharp.Metadata __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::AcidSharp.Metadata(native.ToPointer(), skipVTables);
        }

        internal static global::AcidSharp.Metadata __CreateInstance(global::AcidSharp.Metadata.__Internal native, bool skipVTables = false)
        {
            return new global::AcidSharp.Metadata(native, skipVTables);
        }

        private static void* __CopyValue(global::AcidSharp.Metadata.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Metadata.__Internal));
            *(global::AcidSharp.Metadata.__Internal*) ret = native;
            return ret.ToPointer();
        }

        private Metadata(global::AcidSharp.Metadata.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Metadata(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }
    }

    /// <summary>Holds a RGBA colour.</summary>
    public unsafe partial class Colour : IDisposable
    {
        [StructLayout(LayoutKind.Explicit, Size = 16)]
        public partial struct __Internal
        {
            [FieldOffset(0)]
            internal global::AcidSharp.Colour._.__Internal _;

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@XZ")]
            internal static extern global::System.IntPtr ctor(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@AEBM000@Z")]
            internal static extern global::System.IntPtr ctor(global::System.IntPtr instance, float* r, float* g, float* b, float* a);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBM@Z")]
            internal static extern global::System.IntPtr ctor(global::System.IntPtr instance, global::System.IntPtr hex, float* a);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@AEBV01@@Z")]
            internal static extern global::System.IntPtr cctor(global::System.IntPtr instance, global::System.IntPtr source);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@AEBVVector3@1@AEBM@Z")]
            internal static extern global::System.IntPtr ctor_1(global::System.IntPtr instance, global::System.IntPtr source, float* a);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??0Colour@acid@@QEAA@AEBVVector4@1@@Z")]
            internal static extern global::System.IntPtr ctor_1(global::System.IntPtr instance, global::System.IntPtr source);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Add@Colour@acid@@QEBA?AV12@AEBV12@@Z")]
            internal static extern void Add(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Subtract@Colour@acid@@QEBA?AV12@AEBV12@@Z")]
            internal static extern void Subtract(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Multiply@Colour@acid@@QEBA?AV12@AEBV12@@Z")]
            internal static extern void Multiply(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Divide@Colour@acid@@QEBA?AV12@AEBV12@@Z")]
            internal static extern void Divide(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Scale@Colour@acid@@QEBA?AV12@AEBM@Z")]
            internal static extern void Scale(global::System.IntPtr instance, global::System.IntPtr @return, float* scalar);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Normalize@Colour@acid@@QEBA?AV12@XZ")]
            internal static extern void Normalize(global::System.IntPtr instance, global::System.IntPtr @return);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Interpolate@Colour@acid@@QEBA?AV12@AEBV12@M@Z")]
            internal static extern void Interpolate(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr other, float blend);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SmoothDamp@Colour@acid@@QEBA?AV12@AEBV12@0@Z")]
            internal static extern void SmoothDamp(global::System.IntPtr instance, global::System.IntPtr @return, global::System.IntPtr target, global::System.IntPtr rate);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Decode@Colour@acid@@QEAAXAEBVMetadata@2@@Z")]
            internal static extern void Decode(global::System.IntPtr instance, global::System.IntPtr metadata);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Encode@Colour@acid@@QEBAXAEAVMetadata@2@@Z")]
            internal static extern void Encode(global::System.IntPtr instance, global::System.IntPtr metadata);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??8Colour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorEqualEqual(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??9Colour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorExclaimEqual(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??MColour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorLess(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??NColour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorLessEqual(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??OColour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorGreater(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??PColour@acid@@QEBA_NAEBV01@@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorGreaterEqual(global::System.IntPtr instance, global::System.IntPtr other);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??8Colour@acid@@QEBA_NAEBM@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorEqualEqual(global::System.IntPtr instance, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??9Colour@acid@@QEBA_NAEBM@Z")]
            [return: MarshalAs(UnmanagedType.I1)]
            internal static extern bool OperatorExclaimEqual(global::System.IntPtr instance, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?ToString@Colour@acid@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ")]
            internal static extern void ToString(global::System.IntPtr instance, global::System.IntPtr @return);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Hacid@@YA?AVColour@0@AEBV10@0@Z")]
            internal static extern void OperatorPlus(global::System.IntPtr @return, global::System.IntPtr left, global::System.IntPtr right);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Gacid@@YA?AVColour@0@AEBV10@0@Z")]
            internal static extern void OperatorMinus(global::System.IntPtr @return, global::System.IntPtr left, global::System.IntPtr right);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Dacid@@YA?AVColour@0@AEBV10@0@Z")]
            internal static extern void OperatorStar(global::System.IntPtr @return, global::System.IntPtr left, global::System.IntPtr right);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Kacid@@YA?AVColour@0@AEBV10@0@Z")]
            internal static extern void OperatorSlash(global::System.IntPtr @return, global::System.IntPtr left, global::System.IntPtr right);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Hacid@@YA?AVColour@0@AEBMAEBV10@@Z")]
            internal static extern void OperatorPlus(global::System.IntPtr @return, float* value, global::System.IntPtr left);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Gacid@@YA?AVColour@0@AEBMAEBV10@@Z")]
            internal static extern void OperatorMinus(global::System.IntPtr @return, float* value, global::System.IntPtr left);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Dacid@@YA?AVColour@0@AEBMAEBV10@@Z")]
            internal static extern void OperatorStar(global::System.IntPtr @return, float* value, global::System.IntPtr left);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Kacid@@YA?AVColour@0@AEBMAEBV10@@Z")]
            internal static extern void OperatorSlash(global::System.IntPtr @return, float* value, global::System.IntPtr left);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Hacid@@YA?AVColour@0@AEBV10@AEBM@Z")]
            internal static extern void OperatorPlus(global::System.IntPtr @return, global::System.IntPtr left, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Gacid@@YA?AVColour@0@AEBV10@AEBM@Z")]
            internal static extern void OperatorMinus(global::System.IntPtr @return, global::System.IntPtr left, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Dacid@@YA?AVColour@0@AEBV10@AEBM@Z")]
            internal static extern void OperatorStar(global::System.IntPtr @return, global::System.IntPtr left, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??Kacid@@YA?AVColour@0@AEBV10@AEBM@Z")]
            internal static extern void OperatorSlash(global::System.IntPtr @return, global::System.IntPtr left, float* value);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="??AColour@acid@@QEAAAEAMAEBI@Z")]
            internal static extern float* OperatorSubscript(global::System.IntPtr instance, uint* index);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetR@Colour@acid@@QEBAMXZ")]
            internal static extern float GetR(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetR@Colour@acid@@QEAAXAEBM@Z")]
            internal static extern void SetR(global::System.IntPtr instance, float* r);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetG@Colour@acid@@QEBAMXZ")]
            internal static extern float GetG(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetG@Colour@acid@@QEAAXAEBM@Z")]
            internal static extern void SetG(global::System.IntPtr instance, float* g);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetB@Colour@acid@@QEBAMXZ")]
            internal static extern float GetB(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetB@Colour@acid@@QEAAXAEBM@Z")]
            internal static extern void SetB(global::System.IntPtr instance, float* b);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetA@Colour@acid@@QEBAMXZ")]
            internal static extern float GetA(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?SetA@Colour@acid@@QEAAXAEBM@Z")]
            internal static extern void SetA(global::System.IntPtr instance, float* a);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?LengthSquared@Colour@acid@@QEBAMXZ")]
            internal static extern float LengthSquared(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?Length@Colour@acid@@QEBAMXZ")]
            internal static extern float Length(global::System.IntPtr instance);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetUnit@Colour@acid@@QEBA?AV12@XZ")]
            internal static extern void GetUnit(global::System.IntPtr instance, global::System.IntPtr @return);

            [SuppressUnmanagedCodeSecurity]
            [DllImport("Acid", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="?GetHex@Colour@acid@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ")]
            internal static extern void GetHex(global::System.IntPtr instance, global::System.IntPtr @return);
        }

        public unsafe partial struct _
        {
            [StructLayout(LayoutKind.Explicit, Size = 16)]
            public partial struct __Internal
            {
                [FieldOffset(0)]
                internal global::AcidSharp.Colour._.__.__Internal __;

                [FieldOffset(0)]
                internal global::AcidSharp.Colour._.__.__Internal __1;
            }

            public unsafe partial class __
            {
                [StructLayout(LayoutKind.Explicit, Size = 16)]
                public partial struct __Internal
                {
                    [FieldOffset(0)]
                    internal fixed float m_elements[4];
                }
            }
        }

        public global::System.IntPtr __Instance { get; protected set; }

        protected int __PointerAdjustment;
        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::AcidSharp.Colour> NativeToManagedMap = new global::System.Collections.Concurrent.ConcurrentDictionary<IntPtr, global::AcidSharp.Colour>();
        protected void*[] __OriginalVTables;

        protected bool __ownsNativeInstance;

        internal static global::AcidSharp.Colour __CreateInstance(global::System.IntPtr native, bool skipVTables = false)
        {
            return new global::AcidSharp.Colour(native.ToPointer(), skipVTables);
        }

        internal static global::AcidSharp.Colour __CreateInstance(global::AcidSharp.Colour.__Internal native, bool skipVTables = false)
        {
            return new global::AcidSharp.Colour(native, skipVTables);
        }

        private static void* __CopyValue(global::AcidSharp.Colour.__Internal native)
        {
            var ret = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            global::AcidSharp.Colour.__Internal.cctor(ret, new global::System.IntPtr(&native));
            return ret.ToPointer();
        }

        private Colour(global::AcidSharp.Colour.__Internal native, bool skipVTables = false)
            : this(__CopyValue(native), skipVTables)
        {
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
        }

        protected Colour(void* native, bool skipVTables = false)
        {
            if (native == null)
                return;
            __Instance = new global::System.IntPtr(native);
        }

        /// <summary>Constructor for colour.</summary>
        public Colour()
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            __Internal.ctor((__Instance + __PointerAdjustment));
        }

        /// <summary>Constructor for colour.</summary>
        /// <param name="r">The new R value.</param>
        /// <param name="g">The new G value.</param>
        /// <param name="b">The new B value.</param>
        /// <param name="a">The new A value.</param>
        public Colour(float r, float g, float b, float a)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            var __arg0 = &r;
            var __arg1 = &g;
            var __arg2 = &b;
            var __arg3 = &a;
            __Internal.ctor((__Instance + __PointerAdjustment), __arg0, __arg1, __arg2, __arg3);
        }

        /// <summary>Constructor for colour.</summary>
        /// <param name="hex">The new values from HEX.</param>
        /// <param name="a">The new A value.</param>
        public Colour(string hex, float a)
        {
        //   __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
        //   __ownsNativeInstance = true;
        //   NativeToManagedMap[__Instance] = this;
        //   var __allocator0 = new global::Std.Allocator<char>();
        //   var __basicString0 = global::Std.BasicStringExtensions.BasicString(hex, __allocator0);
        //   var __arg0 = __basicString0.__Instance;
        //   var __arg1 = &a;
        //   __Internal.ctor((__Instance + __PointerAdjustment), __arg0, __arg1);
        //   __basicString0.Dispose(false);
        //   __allocator0.Dispose();
        }

        /// <summary>Constructor for colour.</summary>
        /// <param name="source">Creates this colour out of a existing one.</param>
        public Colour(global::AcidSharp.Colour source)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(source, null))
                throw new global::System.ArgumentNullException("source", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = source.__Instance;
            __Internal.cctor((__Instance + __PointerAdjustment), __arg0);
        }

        /// <summary>Constructor for colour.</summary>
        /// <param name="source">Creates this colour out of a existing vector.</param>
        /// <param name="a">The new A value.</param>
        public Colour(global::AcidSharp.Vector3 source, float a)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(source, null))
                throw new global::System.ArgumentNullException("source", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = source.__Instance;
            var __arg1 = &a;
            __Internal.ctor_1((__Instance + __PointerAdjustment), __arg0, __arg1);
        }

        /// <summary>Constructor for colour.</summary>
        /// <param name="source">Creates this colour out of a existing vector.</param>
        public Colour(global::AcidSharp.Vector4 source)
        {
            __Instance = Marshal.AllocHGlobal(sizeof(global::AcidSharp.Colour.__Internal));
            __ownsNativeInstance = true;
            NativeToManagedMap[__Instance] = this;
            if (ReferenceEquals(source, null))
                throw new global::System.ArgumentNullException("source", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = source.__Instance;
            __Internal.ctor_1((__Instance + __PointerAdjustment), __arg0);
        }

        public void Dispose()
        {
            Dispose(disposing: true);
        }

        public virtual void Dispose(bool disposing)
        {
            if (__Instance == IntPtr.Zero)
                return;
            global::AcidSharp.Colour __dummy;
            NativeToManagedMap.TryRemove(__Instance, out __dummy);
            if (__ownsNativeInstance)
                Marshal.FreeHGlobal(__Instance);
            __Instance = IntPtr.Zero;
        }

        /// <summary>Adds this vector to another vector.</summary>
        /// <param name="other">The other vector.</param>
        public global::AcidSharp.Colour Add(global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = other.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Add((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Subtracts this vector to another vector.</summary>
        /// <param name="other">The other vector.</param>
        public global::AcidSharp.Colour Subtract(global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = other.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Subtract((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Multiplies this vector with another vector.</summary>
        /// <param name="other">The other vector.</param>
        public global::AcidSharp.Colour Multiply(global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = other.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Multiply((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Divides this vector by another vector.</summary>
        /// <param name="other">The other vector.</param>
        public global::AcidSharp.Colour Divide(global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = other.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Divide((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Scales this vector by a scalar.</summary>
        /// <param name="scalar">The scalar value.</param>
        public global::AcidSharp.Colour Scale(float scalar)
        {
            var __arg0 = &scalar;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Scale((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Normalizes this vector.</summary>
        public global::AcidSharp.Colour Normalize()
        {
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Normalize((__Instance + __PointerAdjustment), new IntPtr(&__ret));
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Interpolates between this and another colour.</summary>
        /// <param name="other">The other colour.</param>
        /// <param name="blend">The blend factor.</param>
        public global::AcidSharp.Colour Interpolate(global::AcidSharp.Colour other, float blend)
        {
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = other.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.Interpolate((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0, blend);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        /// <summary>Gradually changes this vector to a target.</summary>
        /// <param name="target">The target vector.</param>
        /// <param name="rate">The rate to go from current to the target.</param>
        public global::AcidSharp.Colour SmoothDamp(global::AcidSharp.Colour target, global::AcidSharp.Colour rate)
        {
            if (ReferenceEquals(target, null))
                throw new global::System.ArgumentNullException("target", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = target.__Instance;
            if (ReferenceEquals(rate, null))
                throw new global::System.ArgumentNullException("rate", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = rate.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.SmoothDamp((__Instance + __PointerAdjustment), new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public void Decode(global::AcidSharp.Metadata metadata)
        {
            if (ReferenceEquals(metadata, null))
                throw new global::System.ArgumentNullException("metadata", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = metadata.__Instance;
            __Internal.Decode((__Instance + __PointerAdjustment), __arg0);
        }

        public void Encode(global::AcidSharp.Metadata metadata)
        {
            if (ReferenceEquals(metadata, null))
                throw new global::System.ArgumentNullException("metadata", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = metadata.__Instance;
            __Internal.Encode((__Instance + __PointerAdjustment), __arg0);
        }

        public static bool operator ==(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            bool __opNull = ReferenceEquals(__op, null);
            bool otherNull = ReferenceEquals(other, null);
            if (__opNull || otherNull)
                return __opNull && otherNull;
            var __arg0 = __op.__Instance;
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorEqualEqual(__arg0, __arg1);
            return __ret;
        }

        public override bool Equals(object obj)
        {
            return this == obj as global::AcidSharp.Colour;
        }

        public override int GetHashCode()
        {
            if (__Instance == global::System.IntPtr.Zero)
                return global::System.IntPtr.Zero.GetHashCode();
            return (*(global::AcidSharp.Colour.__Internal*) __Instance).GetHashCode();
        }

        public static bool operator !=(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            bool __opNull = ReferenceEquals(__op, null);
            bool otherNull = ReferenceEquals(other, null);
            if (__opNull || otherNull)
                return !(__opNull && otherNull);
            var __arg0 = __op.__Instance;
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorExclaimEqual(__arg0, __arg1);
            return __ret;
        }

        public static bool operator <(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(__op, null))
                throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = __op.__Instance;
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorLess(__arg0, __arg1);
            return __ret;
        }

        public static bool operator <=(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(__op, null))
                throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = __op.__Instance;
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorLessEqual(__arg0, __arg1);
            return __ret;
        }

        public static bool operator >(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(__op, null))
                throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = __op.__Instance;
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorGreater(__arg0, __arg1);
            return __ret;
        }

        public static bool operator >=(global::AcidSharp.Colour __op, global::AcidSharp.Colour other)
        {
            if (ReferenceEquals(__op, null))
                throw new global::System.ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = __op.__Instance;
            if (ReferenceEquals(other, null))
                throw new global::System.ArgumentNullException("other", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = other.__Instance;
            var __ret = __Internal.OperatorGreaterEqual(__arg0, __arg1);
            return __ret;
        }

        public static bool operator ==(global::AcidSharp.Colour __op, float value)
        {
            bool __opNull = ReferenceEquals(__op, null);
            bool valueNull = ReferenceEquals(value, null);
            if (__opNull || valueNull)
                return __opNull && valueNull;
            var __arg0 = __op.__Instance;
            var __arg1 = &value;
            var __ret = __Internal.OperatorEqualEqual(__arg0, __arg1);
            return __ret;
        }

        public static bool operator !=(global::AcidSharp.Colour __op, float value)
        {
            bool __opNull = ReferenceEquals(__op, null);
            bool valueNull = ReferenceEquals(value, null);
            if (__opNull || valueNull)
                return !(__opNull && valueNull);
            var __arg0 = __op.__Instance;
            var __arg1 = &value;
            var __ret = __Internal.OperatorExclaimEqual(__arg0, __arg1);
            return __ret;
        }

        public string ToString()
        {
            var __ret = new global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C();
            __Internal.ToString((__Instance + __PointerAdjustment), new IntPtr(&__ret));
            var __basicStringRet0 = global::Std.BasicString<char, global::Std.CharTraits<char>, global::Std.Allocator<char>>.__CreateInstance(__ret);
            var __stringRet0 = global::Std.BasicStringExtensions.CStr(__basicStringRet0);
            __basicStringRet0.Dispose(false);
            return __stringRet0;
        }

        public static implicit operator global::AcidSharp.Colour(global::AcidSharp.Vector4 source)
        {
            return new global::AcidSharp.Colour(source);
        }

        public static global::AcidSharp.Colour operator +(global::AcidSharp.Colour left, global::AcidSharp.Colour right)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            if (ReferenceEquals(right, null))
                throw new global::System.ArgumentNullException("right", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = right.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorPlus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator -(global::AcidSharp.Colour left, global::AcidSharp.Colour right)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            if (ReferenceEquals(right, null))
                throw new global::System.ArgumentNullException("right", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = right.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorMinus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator *(global::AcidSharp.Colour left, global::AcidSharp.Colour right)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            if (ReferenceEquals(right, null))
                throw new global::System.ArgumentNullException("right", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = right.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorStar(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator /(global::AcidSharp.Colour left, global::AcidSharp.Colour right)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            if (ReferenceEquals(right, null))
                throw new global::System.ArgumentNullException("right", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = right.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorSlash(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator +(float value, global::AcidSharp.Colour left)
        {
            var __arg0 = &value;
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = left.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorPlus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator -(float value, global::AcidSharp.Colour left)
        {
            var __arg0 = &value;
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = left.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorMinus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator *(float value, global::AcidSharp.Colour left)
        {
            var __arg0 = &value;
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = left.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorStar(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator /(float value, global::AcidSharp.Colour left)
        {
            var __arg0 = &value;
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg1 = left.__Instance;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorSlash(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator +(global::AcidSharp.Colour left, float value)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            var __arg1 = &value;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorPlus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator -(global::AcidSharp.Colour left, float value)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            var __arg1 = &value;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorMinus(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator *(global::AcidSharp.Colour left, float value)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            var __arg1 = &value;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorStar(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour operator /(global::AcidSharp.Colour left, float value)
        {
            if (ReferenceEquals(left, null))
                throw new global::System.ArgumentNullException("left", "Cannot be null because it is a C++ reference (&).");
            var __arg0 = left.__Instance;
            var __arg1 = &value;
            var __ret = new global::AcidSharp.Colour.__Internal();
            __Internal.OperatorSlash(new IntPtr(&__ret), __arg0, __arg1);
            return global::AcidSharp.Colour.__CreateInstance(__ret);
        }

        public static global::AcidSharp.Colour Clear
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?CLEAR@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Black
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?BLACK@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Grey
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?GREY@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Silver
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?SILVER@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour White
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?WHITE@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Maroon
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?MAROON@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Red
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?RED@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Olive
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?OLIVE@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Yellow
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?YELLOW@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Green
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?GREEN@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Lime
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?LIME@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Teal
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?TEAL@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Aqua
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?AQUA@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Navy
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?NAVY@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Blue
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?BLUE@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Purple
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?PURPLE@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public static global::AcidSharp.Colour Fuchsia
        {
            get
            {
                var __ptr = (global::AcidSharp.Colour.__Internal*)CppSharp.SymbolResolver.ResolveSymbol("Acid", "?FUCHSIA@Colour@acid@@2V12@B");
                return global::AcidSharp.Colour.__CreateInstance(*__ptr);
            }
        }

        public float this[uint index]
        {
            get
            {
                var __arg0 = &index;
                var __ret = __Internal.OperatorSubscript((__Instance + __PointerAdjustment), __arg0);
                return *__ret;
            }

            set
            {
                var __arg0 = &index;
                *global::AcidSharp.Colour.__Internal.OperatorSubscript((__Instance + __PointerAdjustment), &index) = value;
            }
        }

        public float R
        {
            get
            {
                var __ret = __Internal.GetR((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetR((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float G
        {
            get
            {
                var __ret = __Internal.GetG((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetG((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float B
        {
            get
            {
                var __ret = __Internal.GetB((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetB((__Instance + __PointerAdjustment), __arg0);
            }
        }

        public float A
        {
            get
            {
                var __ret = __Internal.GetA((__Instance + __PointerAdjustment));
                return __ret;
            }

            set
            {
                var __arg0 = &value;
                __Internal.SetA((__Instance + __PointerAdjustment), __arg0);
            }
        }

        /// <summary>Gets the length squared of this vector.</summary>
        public float LengthSquared
        {
            get
            {
                var __ret = __Internal.LengthSquared((__Instance + __PointerAdjustment));
                return __ret;
            }
        }

        /// <summary>Gets the length of this vector.</summary>
        public float Length
        {
            get
            {
                var __ret = __Internal.Length((__Instance + __PointerAdjustment));
                return __ret;
            }
        }

        /// <summary>Gets a colour representing the unit value of this colour.</summary>
        public global::AcidSharp.Colour Unit
        {
            get
            {
                var __ret = new global::AcidSharp.Colour.__Internal();
                __Internal.GetUnit((__Instance + __PointerAdjustment), new IntPtr(&__ret));
                return global::AcidSharp.Colour.__CreateInstance(__ret);
            }
        }

        /// <summary>Gets the hex code from this colour.</summary>
        public string Hex
        {
            get
            {
                var __ret = new global::Std.BasicString.__Internalc__N_std_S_basic_string__C___N_std_S_char_traits__C___N_std_S_allocator__C();
                __Internal.GetHex((__Instance + __PointerAdjustment), new IntPtr(&__ret));
                var __basicStringRet0 = global::Std.BasicString<char, global::Std.CharTraits<char>, global::Std.Allocator<char>>.__CreateInstance(__ret);
                var __stringRet0 = global::Std.BasicStringExtensions.CStr(__basicStringRet0);
                __basicStringRet0.Dispose(false);
                return __stringRet0;
            }
        }
    }
}
